### ISSUE TITLE
Setup SSL certificate

### ISSUE THREAD

**Issue by dmpayton** [qtile/qtile.org#1]
https://www.qtile.org gives an SSL warning for *.heroku.com.

http://www.startssl.com/
https://devcenter.heroku.com/articles/ssl

Thanks to karlson on IRC for reporting this.

**Comment by tych0** [comment]
Looks like we could do this with letsencrypt on heroku easily enough if we pay for it. Otherwise, I'd be happy to move the website to the same server that hosts tycho.ws, but then I'd have to figure out how to install all our deps, and I'm not sure I know how to do that :). But, I do use letsencrypt for tycho.ws and it rotates things automatically every three months, which is nice.

**Comment by dmpayton** [comment]
I've actually been thinking about qtile.org recently, and I'm starting to convince myself that using a static site generator might be a solid solution moving forward. I recently built fresnopython.com using [Pelican](http://getpelican.com), hosted on Github Pages with an SSL cert, and it's worked out quite nicely.

**Comment by tych0** [comment]
Nice! It seems that we also are super out of date w.r.t. security in our deps, so I'd definitely be +1 on switching to a static site generator.

**Comment by unsungNovelty** [comment]
Hi @dmpayton @tych0!

Is it possible to move ahead with the SSL certificate? 

My ISP injects ads when browsing an http site and I have been bothered by it when browsing the docs website which is becoming more and more often these days. I am pretty sure there are other users in the same spot as me. Would be much appreciated! Thanks in advance.

**Comment by tych0** [comment]
Lots of things should work, it's just if someone has time to do the work to switch it over :)

But yes, it seems like heroku's automatic SSL certs are totally broken :(

**Comment by unsungNovelty** [comment]
@tych0 - Apart from setting up a hugo site, I am pretty much new to webdev. But let me know if there is something I can do on this. Would be happy to jump into it and figure it out.

**Comment by unsungNovelty** [comment]
@tych0 - To Hugo you mean?

**Comment by tych0** [comment]
I'm not particularly concerned with what; hugo, hand coded, or some other static site generator are all fine with me.

**Comment by unsungNovelty** [comment]
@tych0 - Great! I will start working on the website with Hugo as the backend. I will share an update in a week.

**Comment by unsungNovelty** [comment]
@tych0 - Didn't get the time to kick start this last week. But I have started working on it and hopefully have something to show in 3 days time if everything goes well. Or later this week.

**Comment by unsungNovelty** [comment]
Update: It is taking a more time than expected as I got busy in my work schedule. If somebody is planning to do a fast one day project or the sorts, feel free to take this up. _**But I will either way replicate the page and move it into a Hugo website and finish it as a personal project on my own**_. But don't want to block anyone in case there is any emergencies with this cos mine might take a few weeks with my new schedule.

cc:// @tych0

**Comment by elParaguayo** [comment]
@tych0 two things:
1) Our SSL certificate has expired - is this renewable through Heroku?
2) I have made a start on moving the website to a static generator (Pelican) but it's slow going as I'm not a web person!

**Comment by unsungNovelty** [comment]
> Our SSL certificate has expired - is this renewable through Heroku? (EDIT: Did we ever have SSL enabled? I can see we reference the site as http://www.qtile.org/, not https.)

As per @tych0's earlier comment. We did have SSL provisioning which was broken.

> I have made a start on moving the website to a static generator (Pelican) but it's slow going as I'm not a web person. (Actually, I made a start months ago and then got distracted by other, easier things!)

@elParaguayo - I haven't abandoned my effort as well. But same story as yours. Been having a busy work schedule. And that will continue to another month or so. Let me know if you need an extra pair of 👀  on your _end results_ if you are going ahead with this. :)

**Comment by tych0** [comment]
I just checked Heroku, and our SSL certs are set to "automatically managed". However, when I go to https://qtile.org and click through myself, I get redirected to a completely different hosting web page. Something weird is definitely going on.

I'm wondering if it's not time to just scrape the web page as is for the raw HTML, call that a static site for now, and start using that.

**Comment by tych0** [comment]
As it happens, I'll have some free time in a week or so. Perhaps I can look into fixing this in a more reasonable way :)

**Comment by tych0** [comment]
So I think stuff like #3 will need a more complete rewrite than I really have time for; most of that html rendering is generated via django plugins. That said, maybe we drop some of this stuff until someone has time to fix it?

I can't decide whether having the website in its current pretty form is more important than having e.g. SSL and maybe an automatic deploy to Cloudflare Pages or something set up. Perhaps we can automatically deploy from here to heroku, but someone who knows heroku needs to keep our platform level updated, which has historically been a challenge.

**Comment by unsungNovelty** [comment]
Have restarted my work on this. Don't have a timeline to provide yet.

**Note**: _Nothing is polished yet. You will see bits and pieces broken here and there. The screenshots provided wouldn't represent the final product. Especially with typography and colours which are untouched at the time of writing this._
|   Live Demo  | Repo  |
| --- | --- |
| https://effulgent-meerkat-c4cc53.netlify.app/ | https://github.com/unsungNovelty/qtile.org

# Main wins so far:

- Have recreated the Qtile logo as a vector image for ease of use.
- Almost done with Home page.
- Currently working on the Screenshots grid.

# Tech stack:

- Hugo
- HTML
- Tailwind CSS
- JS
- Netlify for hosting and SSL provisioning.

# Logo Recreation

![qtile-logo-black](https://user-images.githubusercontent.com/11845908/167302891-0fa06955-ef3a-4f94-ad27-e343808bdb12.png)

# Screenshots:

![image](https://user-images.githubusercontent.com/11845908/167301985-bb92b3f9-7f16-4368-ab5d-e985a5d1a7b1.png)

---

![image](https://user-images.githubusercontent.com/11845908/167303067-832bed57-d35a-428c-b080-75522e89870f.png)
(Screenshot grid not yet live at the time of writing)

**Comment by tych0** [comment]
Looks like great progress, thank you!

**Comment by tych0** [comment]
Yes +1 to hooks and auto-deploys. When the time comes I'm happy to coordinate the nameserver switch and all that.

**Comment by unsungNovelty** [comment]
@tych0 @elParaguayo - Am glad that the progress is satisfactory to you both. I had to restart from scratch to cleanup my earlier try. While nothing is finalised, appreciate any feedback you might have.

 > Would also be great if we could host on github pages and use hooks to trigger a rebuild of the site whenever we release a new version.

 @elParaguayo @tych0 - I would recommend using Netlify over GitHub pages.

- I would recommend not putting the code and website in the same basket(GitHub). It's just a good practice to follow. And has an added bonus point for resilience. My experience w/ Netlify has been great for the last 3 years.
-  Netlify already provides continuous-deployments, auto SSL provisioning, a CDN and their [pro plan for OSS projects](https://www.netlify.com/legal/open-source-policy/). They also have a generous free-tier (w/ 100GB bandwidth, auto SSL provisioning, CDN and CD) if we don't have to bother with it. So it is in no way a step down to GitHub pages.
- First class [support for Hugo websites](https://gohugo.io/hosting-and-deployment/hosting-on-netlify/). It is just as easy to deploy as GitHub pages. Just a couple of clicks excluding the name server configuration of course.

> When the time comes I'm happy to coordinate the nameserver switch and all that.

Great! I will let you know.

@tych0 - What do you think about dropping google analytics for a privacy friendly and an open source option like [goat counter](https://www.goatcounter.com/)? It has a free hosted service for non-commercial use. It is also [GDPR friendly](https://www.goatcounter.com/help/gdpr) as far as I understand. Would love to hear your thoughts on it.

## To do
- [ ] Fork qtile.org and push changes into a new branch to preserve commit history.

## Updates
- Image processing w/ Hugo. Screenshots for a single screenshot is converted to `.webp` for maximum quality and compression irrespective of what image format is provided by the end user. `.webp` cuts almost half in image size compared to `.jpg/.png`. This means faster load times. I am yet to implement a fallback option for browsers which doesn't yet support `.webp`. It will be done soon.
- Improved the screenshot section. This is how a screenshot page looks like.
![image](https://user-images.githubusercontent.com/11845908/167995452-ca647cdd-0d8e-42c3-89eb-94ae2d0d1e77.png)

- Made embedding youtube videos into the website easier. All you have to do is add `{{< youtube-embed <video id> >}}` inside a markdown file and it will embed a youtube video. Eg; `{{< youtube-embed skT9CZJ7V4Y >}}` will embed https://www.youtube.com/watch?v=skT9CZJ7V4Y. Need to polish it. Consider this a POC.

![image](https://user-images.githubusercontent.com/11845908/167999531-f9a73247-fec9-4733-9078-43a35c845141.png)

**Comment by m-col** [comment]
TIL we use google analytics! Is it even set up correctly from a legal POV? I don't see anything about it on the website. I 100% agree with moving away from that. Goatcounter is pretty nice, I've used it before. But I think Plausible is better and easier to use. It costs, but I was planning on getting a subscription anyway and you can have up to 50 websites so I'm happy to stick qtile.org on it too. We can also make the analytics publicly available because why not.

**Comment by unsungNovelty** [comment]
> I think Plausible is better and easier to use. It costs, but I was planning on getting a subscription anyway and you can have up to 50 websites so I'm happy to stick qtile.org on it too. We can also make the analytics publicly available because why not.

That is great to know. Thanks @m-col! I do have a questions.

AFAIK other plausible websites I know have a GDPR consent notice. Will this mean we will have to have a consent notice too if we use Plausible? I am not a fan of it. From my POV it is a very bad UX. 

I recommended Goat Counter (GC) to avoid a consent notice since [GC website says we don't have to](https://www.goatcounter.com/help/gdpr). Do you have any idea about the legal side of this? Thanks again.

**Comment by m-col** [comment]
I completely agree, avoiding that would be ideal. You don't need a banner for Plausible (it actually looks like their own website doesn't use one). From https://plausible.io/data-policy:

> By using Plausible, you don’t need to have any GDPR, CCPA or PECR prompts and you don’t need [a complex privacy policy](https://plausible.io/blog/privacy-policy-page) about your use of analytics and cookies.

Either way we'd best use a small privacy policy page somewhere. I havent seen the existing GA data so not sure how valuable it is, but we can also import GA data into plausible so we don't need to start fresh which is nice.

**Comment by unsungNovelty** [comment]
> Either way we'd best use a small privacy policy page somewhere. I havent seen the existing GA data so not sure how valuable it is, but we can also import GA data into plausible so we don't need to start fresh which is nice.

Makes sense. I will keep this in mind. [Plausible has documentation for Hugo](https://plausible.io/docs/hugo-integration). Not much different from GC at first glance. I wonder what @tych0 and @elParaguayo's thoughts are on this.

**Comment by elParaguayo** [comment]
I didn't know we used google analytics either!

My only questions is, if no-one's actually looking at any of this data, do we even need it?

**Comment by m-col** [comment]
It could be useful to what parts of the docs are completely ignored and can be redone perhaps

**Comment by tych0** [comment]
> I would recommend not putting the code and website in the same basket(GitHub). It's just a good practice to follow. And has an added bonus point for resilience when github is down.

In general, I'd prefer to use Github simply because it makes managing permissions less of a pain. We don't have to keep track of a whole different permissions structure, forget to add maintainers, etc. I'm not really that concerned with qtile.org's uptime, as it's not mission critical.

> Is it even set up correctly from a legal POV?

Probably not, all this was done many years before GDPR was a thing. I don't even know who has access to the analytics account any more (another argument for minimizing the number of third parties we interact with). I'm fine with just dropping it.

One question I have, without looking through the code: is the config on the front page autogenerated from the code? Or do we need to re-port it for newer config changes?

**Comment by tych0** [comment]
> One question I have, without looking through the code: is the config on the front page autogenerated from the code? Or do we need to re-port it for newer config changes?

Answering my own question here - looks like it's just copy pasted into home.md. I wonder if there's a way we can auto-generate this?

**Comment by unsungNovelty** [comment]
> It could be useful to see what parts of the docs are completely ignored and can be redone perhaps

@m-col On second thoughts, I am not sure if this will yield any significant benefits if we are to use _basic analytics_. Cos all you would find out is the most common parts of the documentation. Once we know that, there isn't anything else. Irrespective of whether it is up to date or not, people will go to the popular parts of the document. The only actionable way would be them reporting it. 

> In general, I'd prefer to use Github simply because it makes managing permissions less of a pain. We don't have to keep track of a whole different permissions structure, forget to add maintainers, etc. I'm not really that concerned with qtile.org's uptime, as it's not mission critical.

Understood. 👍🏽

> Probably not, all this was done many years before GDPR was a thing. I don't even know who has access to the analytics account any more (another argument for minimizing the number of third parties we interact with). I'm fine with just dropping it.

+1 on this.

> Answering my own question here - looks like it's just copy pasted into home.md. I wonder if there's a way we can auto-generate this?

@tych0 - You are right. It is just a copy-paste from `home.md`. But maybe we can trigger this based on rebuilds. That is every time we run `hugo` command which will rebuild the site, you look for a particular source and update it or something. Somewhere like [default config file from the documentation](https://docs.qtile.org/en/stable/manual/config/default.html) so that we don't have to duplicate the effort. But I don't see any api or anything from which we can pull the info. Haven't used Read the docs ever, so maybe I am missing something?

**Comment by elParaguayo** [comment]
Re `default_config.py`: In my attempt to move this to Pelican, I had made an extension that downloaded the config from the latest tagged release whenever the site was built (https://github.com/elParaguayo/qtile.org/blob/pelican-migration/extensions/config.py). Presumably we can do something similar here.

Also note that the default_config file is in our docs too: http://docs.qtile.org/en/stable/manual/config/default.html

**Comment by unsungNovelty** [comment]
Qtile repo forked and will be pushing to https://github.com/unsungNovelty/qtile.org/tree/qtile-hugo going forward. Hugo site is in `qtile-hugo` branch for now. The site is not working yet. Will update with progress soon.

**Comment by unsungNovelty** [comment]
# Update 08/05/2023
I restarted my work the other day. I have replicated and ported the qtile site to hugo in it's entirety. All the screenshots, videos things like fonts and everything. The goal has been to replicate the old site in Hugo before UI changes.

The only thing that is left is known issues, some small improvements and documentations for contributing. Documentation on the basics of hugo and tailwindcss so that people can jump right away. It shouldn't be much work. There is obviously improvements to be made here and there. Fixing known issues and other things. That is what I will be doing over the next week or so. I will update further progress on [this comment](https://github.com/qtile/qtile.org/issues/1#issuecomment-1161927820). And excuse the delay on this.

| Description | URL
| --------------- | ------
| Working Repo | https://github.com/unsungNovelty/qtile.org/tree/qtile-hugo
| Netlify demo site | https://exquisite-seahorse-3019e9.netlify.app

# Screenshots
![image](https://user-images.githubusercontent.com/11845908/236735518-10ec049e-716d-402c-a1c0-4a50fc60158c.png)
---
![image](https://user-images.githubusercontent.com/11845908/236735588-88dd1d19-3ea2-4e62-afc8-1da2562ed03b.png)
---
![image](https://user-images.githubusercontent.com/11845908/236735657-254e3597-b7d0-446b-921a-e30c0cfd6332.png)
---
![image](https://user-images.githubusercontent.com/11845908/236735707-22c8f66b-5c52-426f-af13-84acbc12763a.png)

# Known issues:
- Screenshot section doesn't account for the absence of config files.

@tych0 @m-col @elParaguayo - Please poke around. Any feedback would be great.

**Comment by unsungNovelty** [comment]
# Update 08/05/2023
I restarted my work the other day. I have replicated and ported the qtile site to hugo in it's entirety. All the screenshots, videos things like fonts and everything. The goal has been to replicate the old site in Hugo before any big UI changes.

The only thing that is left is documentations for contributing. Documentation on the basics of hugo and tailwindcss so that people can jump right away. It shouldn't be much work. There is obviously improvements to be made here and there. Fixing known issues and other things. That is what I will be doing over the next week or so. I will update further progress on [this comment](https://github.com/qtile/qtile.org/issues/1#issuecomment-1161927820). And excuse the delay on this.

| Description | URL
| --------------- | ------
| Working Repo | https://github.com/unsungNovelty/qtile.org/tree/qtile-hugo
| Netlify demo site | https://exquisite-seahorse-3019e9.netlify.app

# Screenshots
![image](https://user-images.githubusercontent.com/11845908/236735518-10ec049e-716d-402c-a1c0-4a50fc60158c.png)
---
![image](https://user-images.githubusercontent.com/11845908/236735588-88dd1d19-3ea2-4e62-afc8-1da2562ed03b.png)
---
![image](https://user-images.githubusercontent.com/11845908/236735657-254e3597-b7d0-446b-921a-e30c0cfd6332.png)
---
![image](https://user-images.githubusercontent.com/11845908/236735707-22c8f66b-5c52-426f-af13-84acbc12763a.png)

# Known issues:
- Screenshot section doesn't account for the absence of config files.

@tych0 @m-col @elParaguayo - Please poke around. Any feedback would be great.

**Comment by tych0** [comment]
Broadly I think this looks awesome. Two things I noticed are:

* version info is wrong
* bad quoting in the sample config on the front page (e.g. `{&#x27;wmclass&#x27;: &#x27;confirm&#x27;},`), but this exists in qtile.org right now and is not a blocker IMO.

I recently (~2 weeks ago maybe) got a nastygram from Heroku about how our stack is super old, so I think it's worth trying to migrate asap. I propose the following:

1. you make your PR to switch this repo to your new version
2. someone (I'll volunteer, although it'll probably be a week or two) maps that to qtile.github.io for now, so we can test automatic build/publish of the web page, fix minor nits, etc.
3. we get cortesi to switch the qtile dns according to this to make it live: https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site/managing-a-custom-domain-for-your-github-pages-site#configuring-an-apex-domain

I'd say go ahead and make your PR with what you currently have, I and I'm sure others are happy to help fix up minor nits once we have the build infra going.

**Comment by tych0** [comment]
Oh, and thank you for this! qtile.org was going to fall over soon without someone having done this, so it is important!

**Comment by elParaguayo** [comment]
Agreed with everything Tych0 says. Thank you so much for doing this.

**Comment by unsungNovelty** [comment]
@tych0 @elParaguayo - Great! I will try to make the PR tomorrow morning IST hours or in the evening.

**Comment by unsungNovelty** [comment]
@tych0 @elParaguayo @m-col - PR has been opened - https://github.com/qtile/qtile.org/pull/44. Please let me know how I can assist with Hugo or Tailwind CSS. I am on the Qtile Telegram Channel if you need me for anything.

**Comment by unsungNovelty** [comment]
@tych0 - While making `qtile.github.io` live, do remove [`.hugo_build.lock`](https://github.com/qtile/qtile.org/blob/master/.hugo_build.lock) file. It is a build file for netlify which is not necessary anymore.

**Comment by tych0** [comment]
sure, can you send a PR to delete it?

**Comment by unsungNovelty** [comment]
@tych0 - Will do.

**Comment by jwijenbergh** [comment]
Thanks a lot for the hard work @unsungNovelty! Hugo is awesome

**Comment by tych0** [comment]
https://qtile.github.io is alive!

I'm inclined to just go ahead and set it up to push, given the broken state of heroku and that it's hard to push new content to it. Any objections?

**Comment by elParaguayo** [comment]
None from me.

**Comment by unsungNovelty** [comment]
@tych0 - None from me either. I was wondering, how do I get access to wiki in the repo so that I can add basic info on Hugo and setting up the basic dev environment and stuff? Do I need to have access to the repo?

Also, working on the documentation and bug fixes. Will hopefully have something to show in the coming days.

**Comment by tych0** [comment]
I would say don't bother with the wiki, just write a readme and put it in the main repo. I almost started one to talk about the deployment strategy.

**Comment by unsungNovelty** [comment]
@tych0 - Agreed. I will open a PR tomorrow.

**Comment by unsungNovelty** [comment]
@tych0 - README.md PR is up - https://github.com/qtile/qtile.org/pull/47. Do let me know if you need any changes or if something needs to be added.

**Comment by elParaguayo** [comment]
@tych0 - looks like docs.qtile.org, which points to the readthedocs page, isn't secure either.

**Comment by tych0** [comment]
I think it's just a matter of https everywhere style rewriting. https://docs.readthedocs.io/en/stable/custom-domains.html#how-custom-domains-work says it's automatic, and https://docs.qtile.org works for me.

**Comment by elParaguayo** [comment]
Strange. Works for me now. Thanks.

**Comment by unsungNovelty** [comment]
@tych0 - Looks like the SSL certificate still points to the old one that is configured to qtile.org?
I was with the impression that github pages uses Let's Encrypt's certificate.

**Comment by tych0** [comment]
Yup, the domain is still hosed. We’re just waiting for cortesi to fix it.

**Comment by unsungNovelty** [comment]
Forgot to give credits to @arkarjun for his inkscape magic. 
He recreated the qtile logo used in the home page and navbar. 
We used to use fontawesome's icon Q + the text "tile".
Thanks Arjun!

**Comment by elParaguayo** [comment]
I think the previous website used a power logo that was rotated!

**Comment by unsungNovelty** [comment]
> I think the previous website used a power logo that was rotated!

@elParaguayo - Yes, you're right. By Fontawesome's Q I meant the power button. 
@arkarjun used that setup and recreated that with Varela round font we use and made it in to a single image.

We use it in three places:
- Navbar, Home page Title - https://qtile.org/images/qtile-logo-white.webp
- Footer - https://qtile.org/images/qtile-logo-black.png
