### ISSUE TITLE
Pushing a new version deletes the CNAME

### ISSUE THREAD

**Issue by ramnes** [qtile/qtile.org#50]
When we push a new version, the other repo gets its CNAME file deleted, giving a 404 to qtile.org and deleting the TLS certificate: https://github.com/qtile/qtile.github.io/commit/a3b4596b7be835d0f23a293d5400b04d7f276d2a

cc @tych0

**Comment by tych0** [comment]
heh. so maybe we need to rename this repo and do it all as one?

**Comment by tych0** [comment]
two reasons: 1. keep qtile.org discoverable as a repo (the github pages repo has to be name qtile.github.io), and 2. keep the autogenerated gunk out of the qtile.org repo so that we don't bloat it.

i agree we don't want to override CNAME all the time; i won't have time to look at it for a bit though.

**Comment by ramnes** [comment]
Fixed in 9d18ad4030694de06cabcc75342ebd464e091ef7

**Comment by tych0** [comment]
Nice, thanks!
